### PR TITLE
Remove generic `AbstractArray` fallbacks for `position`

### LINKED ISSUE #16: [ENHANCEMENT] Decide on default position definitions for `eltype` and `ndims`
Right now there is a generic definition for any `AbstractArray` subtype that the first parameter is `eltype` and the second is `ndims`, that is of course incorrect for some `AbstractArray` subtypes but it is a very convenient definition since most `AbstractArray`s follow that convention.

### PR DESCRIPTION
**Pull request by mtfishman**
Closes #16. This removes generic fallback definitions for the positions of `eltype` and `ndims` for AbstractArrays, which is safer since not all of them have `eltype` in the first position and `ndims` in the second position.

This was inspired by a bug I was hunting down while working on https://github.com/ITensor/QuantumOperatorDefinitions.jl/pull/22, which was due to a `BitArray` using the generic position definition, which was incorrect because it doesn't have an `eltype` parameter since it is always `Bool`, and `ndims` is in the first position. In this PR, I added explicit correct definitions for `BitArray`.

@lkdvos @kmp5VT

I think this will be a good move. One issue this PR reminds me of is that right now default parameters are defined like:
```julia
default_type_parameters(::Type{<:Array}) = (Float64, 1)
```
i.e. they are defined in a list. This is ok, but I think it would be nicer if we could define them one at a time using the parameter names:
```julia
default_type_parameter(::Type{<:Array}, eltype) = Float64
default_type_parameter(::Type{<:Array}, ndims) = 1
```
I remember we tried that earlier on and it was tough to make type stable, but I think it would be good to revisit that (but not in this PR). (**EDIT:** Raised an issue here: #27.)

### CODE REVIEW

File: src/base/array.jl [hunk 1]
```diff
@@ -1,2 +1,24 @@
...
+# f(AbstractArray{Float64})
+# f(AbstractMatrix{Float64})
+# ```
+# etc.
+const AbstractArrayType{T,N} = Union{
+  Type{AbstractArray},
+  Type{AbstractArray{T}},
+  Type{AbstractArray{<:Any,N}},
+  Type{AbstractArray{T,N}},
+}
```
Comment (lkdvos) [inline src/base/array.jl:14]: This feels a bit clunky, and it looks to me like we should only ever have to define functions for the base type, and then the library should automatically capture reroute to that. I am thinking of something like
```julia
function position(::Type{T}, f) where {T}
  baseT = unspecify_type_parameters(T)
  baseT === T && error("position not defined for $T and $f") # avoid infinite recursion
  return position(baseT, f)
end
```
```

**Review by lkdvos — COMMENTED** [review]
Definitely agree to get rid of that definition, as this clearly might silently give you wrong results.

Also agreed to having the option of specifying defaults one at a time, in a future PR.

File: src/base/array.jl (hunk 1 above)
Comment (mtfishman) [reply src/base/array.jl:14]: That sounds reasonable, I'll try that out.

**Comment by kmp5VT** [comment]
This makes sense to me, I had concerns with these definitions before. Thanks Matt!

File: src/base/array.jl (hunk 1 above)
Comment (mtfishman) [reply src/base/array.jl]: Ok, I've implemented that, looks like a good solution, thanks!

**Comment by mtfishman** [comment]
@lkdvos any more comments?

**Review by lkdvos — APPROVED** [review]
Looks good to me!
